### ISSUE TITLE
Package not displaying output

### ISSUE THREAD

**Issue by PythonPrashant** [SwiftyProgrammer690/fireworks#41]
So, I tried this package and it is not displaying any output!
My code:
`get_user('FSojitra)`

**Comment by SwiftyProgrammer690** [comment]
Hi @PythonPrashant thank you for opening this issue!
It seems as though your problem is that you have to print everything for an output!
Your current code: `get_user('FSojitra')` -> `print(get_user('FSojitra'))` 
That should fix your issue!

**Comment by PythonPrashant** [comment]
I just tried your fix and it works! Thank you!

**Comment by SwiftyProgrammer690** [comment]
Np!
